### ISSUE TITLE
Enable image styles delivery

### ISSUE THREAD

**Issue by fiasco** [acquia/next-acms#37] opened 2022-06-27 22:17 UTC
Make it possible for the starter kit to leverage Drupal image styles. This may require changes to Acquia CMS to support.

This is useful because without knowing the width and height of an image, its impossible to render a derivative in Next.js without obscuring the image. So in lieu, we can provide an option to use a pre-sized version of the image by Drupal.

**Comment by lauriii** [comment] 2022-07-19 13:36
We could use [Consumer Image Styles](https://www.drupal.org/project/consumer_image_styles) module for this. However, that module is not compatible with [JSON:API Hypermedia](https://www.drupal.org/project/jsonapi_hypermedia) which we already use because it's required by [JSON:API Menu Items](https://www.drupal.org/project/jsonapi_menu_items). There's already an issue for this in the Drupal.org issue queue: https://www.drupal.org/project/jsonapi_hypermedia/issues/3121092.

**Comment by lauriii** [comment] 2022-08-04 08:26
Confirmed that with the new release of [JSON:API Hypermedia](https://www.drupal.org/project/jsonapi_hypermedia), I'm able to retrieve links to images using image styles with [Consumer Image Styles](https://www.drupal.org/project/consumer_image_styles).

We need to decide whether to include this as part of basic starter or simply document how this could be used by providing examples. Since Acquia CMS is using focal point by default, I'm leaning towards adding [Consumer Image Styles](https://www.drupal.org/project/consumer_image_styles) to the Acquia CMS Headless starterkit, and provide an example of usage in the basic starter.

**Comment by lauriii** [comment] 2022-09-22 14:33
This has been resolved by #102

**Closed by lauriii** 2022-09-22 14:33 UTC
